# Generated by Django 2.0.3 on 2018-04-03 05:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
