# Generated by Django 2.0.3 on 2018-04-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_auto_20180403_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sess_key',
            field=models.CharField(default='NULL', max_length=32),
        ),
    ]
