# Generated by Django 2.0.4 on 2018-04-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_user_sess_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sess_key',
        ),
    ]
