# Generated by Django 2.0.4 on 2018-04-17 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_remove_user_sess_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)])),
                ('first_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='chatbox.User')),
                ('second_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='chatbox.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default='CS151082EC171013', on_delete=django.db.models.deletion.CASCADE, to='chatbox.Conversation'),
            preserve_default=False,
        ),
    ]
