# Generated by Django 2.0.4 on 2018-04-18 14:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0005_auto_20180417_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(24)]),
        ),
    ]
